/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * login.java
 *
 * Created on Apr 23, 2011, 1:15:12 AM
 */

package javaapplication1;

import java.net.UnknownHostException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;
import java.awt.event.ActionEvent;
import java.awt.*;
import java.net.InetAddress;
import org.jdesktop.swingx.*;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.swing.JOptionPane;

/**
 *
 * @author gun
 */
public class login extends javax.swing.JPanel {

    /** Creates new form login */


    public login() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        loginbutton = new javax.swing.JButton();
        jXHyperlink1 = new org.jdesktop.swingx.JXHyperlink();
        jSeparator1 = new javax.swing.JSeparator();
        jXLoginPane1 = new org.jdesktop.swingx.JXLoginPane();

        loginbutton.setText("Login");
        loginbutton.setName("loginbutton"); // NOI18N
        loginbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginbuttonActionPerformed(evt);
            }
        });

        jXHyperlink1.setText("Register");
        jXHyperlink1.setName("jXHyperlink1"); // NOI18N
        jXHyperlink1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jXHyperlink1ActionPerformed(evt);
            }
        });

        jSeparator1.setName("jSeparator1"); // NOI18N

        jXLoginPane1.setName("jXLoginPane1"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(243, 243, 243)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(637, 637, 637))
            .addGroup(layout.createSequentialGroup()
                .addGap(198, 198, 198)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(137, 137, 137)
                        .addComponent(loginbutton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jXHyperlink1, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE))
                    .addComponent(jXLoginPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(282, 282, 282))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addComponent(jXLoginPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(loginbutton)
                    .addComponent(jXHyperlink1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(267, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jXHyperlink1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jXHyperlink1ActionPerformed
        // TODO add your handling code here:
        Main.x.switchto("register");
        

    }//GEN-LAST:event_jXHyperlink1ActionPerformed

    private void loginbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginbuttonActionPerformed
        try {
            Main.x.taskUser.removeAll();
            // TODO add your handling code here:
            String uname = jXLoginPane1.getUserName();
                    Statement st;
                    ResultSet res;
            Main.con.query("select * from userinfo where username='" + uname + "';");
                    st = Main.con.getResults();
                   res= st.getResultSet();
                   res.next();

                   System.out.println(res.getString("password"));
               
                       if(res.getString("password").equals(String.copyValueOf(jXLoginPane1.getPassword())))
                       {
                           if(!res.next())
                           {
                           JOptionPane.showMessageDialog(this, "successful login");
                          Main.sess.createSession(uname);
                          NewJFrame.jPanel1.add(new profilePane(), "profile");
                          NewJFrame.jPanel1.add(new viewfollowers(), "viewfol");
                          Main.x.populateTaskItems();
                          }
                       
            try {
                InetAddress in = InetAddress.getLocalHost();
                Main.con.query("update userinfo set currentip = '"+in.getHostAddress()+"' where username='" + uname + "';");
                System.out.println(in.toString());
            } catch (UnknownHostException ex) {
                Logger.getLogger(login.class.getName()).log(Level.SEVERE, null, ex);
            }


                  Main.x.switchto("profile");

                  Main.x.taskUser.setTitle("User("+uname+")");


                  Main.x.taskUser.add(new AbstractAction(){
        {
            putValue(Action.NAME,"Logout");
            putValue(Action.SHORT_DESCRIPTION,"");
        }
          public void actionPerformed(ActionEvent e){
       if(JOptionPane.showConfirmDialog(NewJFrame.jPanel1, "Are you sure?", "Message", JOptionPane.YES_NO_OPTION)==0)
                {
                    JOptionPane.showMessageDialog(NewJFrame.jPanel1, "You have successfully logged out");

                Main.x.taskUser.removeAll();
                Main.x.taskListen.setCollapsed(true);
                Main.x.taskMisc.setCollapsed(true);
                Main.x.taskNetwork.setCollapsed(true);
                Main.x.taskSettings.setCollapsed(true);
                Main.x.taskStream.setCollapsed(true);
                Main.x.taskStream.removeAll();
                Main.x.taskNetwork.removeAll();
                Main.x.taskMisc.removeAll();
                Main.x.taskListen.removeAll();
                Main.x.taskUser.setTitle("User");
                Main.x.taskUser.updateUI();
                Main.sess.endSession();
                Main.x.switchto("login");
                Main.x.addlogin();
                Main.x.taskUser.updateUI();
                }
            }
     });
     
                  Main.x.taskUser.add(new AbstractAction(){
        {
            putValue(Action.NAME,"View Information");
            putValue(Action.SHORT_DESCRIPTION,"view Profile Information");
        }
          public void actionPerformed(ActionEvent e){
            Main.x.switchto("profile");
            }
     });
            }
        } catch (SQLException ex) {
            Logger.getLogger(login.class.getName()).log(Level.SEVERE, null, ex);
    }
        


    }//GEN-LAST:event_loginbuttonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSeparator jSeparator1;
    private org.jdesktop.swingx.JXHyperlink jXHyperlink1;
    private org.jdesktop.swingx.JXLoginPane jXLoginPane1;
    private javax.swing.JButton loginbutton;
    // End of variables declaration//GEN-END:variables

}
